compressionLevel: mixed

enableGlobalCache: false

npmScopes:
  video:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.livelyvideo.tv/"
    npmRegistryServer: "https://npm.livelyvideo.tv/"
  videomobile:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.nativeframe.com/"
    npmRegistryServer: "https://npm.nativeframe.com/"
  nativeframe:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://npm.nativeframe.com/"
    npmRegistryServer: "https://npm.nativeframe.com/"
  videorn:
    npmAlwaysAuth: true
    npmPublishRegistry: "https://registry.npmjs.org/"
    npmRegistryServer: "https://registry.npmjs.org/"

yarnPath: .yarn/releases/yarn-3.6.1.cjs
nodeLinker: node-modules
nmHoistingLimits: workspaces #very important or node_modules dir will not build properly
nmMode: hardlinks-global